spring.application.name=viapdv


#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver